global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO

api:
  dashboard: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: aramina_net

certificatesResolvers:
  letsencrypt:
    acme:
      email: rezaabaskhanian1367kash@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
